#!/usr/bin/env bash
# script that automates file transfer from client to user

path_name=$1
ip_add=$2
server_usrnm=$3
ssh_key_path=$4

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -i $ssh_key_path -o StrictHostKeyChecking=no $path_name $server_usrnm@$ip_add:~/
