#!/usr/bin/env bash
# 301 permanently moved execution

sudo apt-get update
# install nginx
sudo apt-get install -y nginx
# echo message and pipe it to create a script in index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html
# create replacement string
replacement_string="server_ name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/kgaugelo-shai permanent;"
# sed command with path to redirect page
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
