#!/usr/bin/env bash
sudo apt-get -y update
apt-get -y install haproxy
config=\
"
frontend  load_balancer_frontend
        bind *:80
        mode http
        default_backend webservers_backend
backend webservers_backend
        balance roundrobin
        server 530775-web-01 54.237.79.35:80 check
        server 530775-web-01 100.26.243.92:80 check
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ACTIVATED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
