#!/usr/bin/env bash
# Displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is a multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise displays the format

for nm in {1..100}
do
  if (( nm % 3 == 0 && nm % 5 == 0))
  then
    echo "FizzBuzz"
  elif (( nm % 3 == 0))
  then
    echo "Fizz"
  elif (( nm % 5 == 0))
  then
    echo "Buzz"
  else
    echo "$nm"
  fi
done