#!/usr/bin/env bash
# Displays "Best School" 10 times
# Then displays "Hi" on the 9th loop

loop=0

while [ $loop -lt 10 ]
do
  if [ $loop -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( loop++ ))
done