#!/usr/bin/env bash
# Loops from 1 to 10 and
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

loop=0

while [ $loop -lt 10 ]
do
  if [ $loop -eq 3 ]
  then
    echo "bad luck"
  elif [ $loop -eq 7 ]
  then
    echo "good luck"
  else
      echo "Best School"
  fi
  (( loop++))
done
